### ISSUE TITLE
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16

### ISSUE THREAD

**Issue by Erriez** [aaronbarnaby/get-tag#9]
## Github action summary:

**Create Github release**
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: 
aaronbarnaby/get-tag@v1.0.0. For more information see: 
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

**Create Github release**
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. 
For more information see: 
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

## Github action test:

```yaml
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: GitHub Tag Name example
        run: |
         echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"

      - name: Extract Tag
        id: tag
        uses: aaronbarnaby/get-tag@v1.0.0
        with:
          without_prefix_v: true # Remove prefix `v` from tag

      - name: Use Tag
        run: |
          echo "Extracted tag version: ${{ steps.tag.outputs.tag }}"
```

## Github action output:
```
Run aaronbarnaby/get-tag@v1.0.0
  with:
    without_prefix_v: true
ref=refs/tags/v1.0.1
tag=1.0.1

Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

@aaronbarnaby Do you have plans to update this useful Github Action?
